### ISSUE TITLE
Clubhouse importer doesn't show in the list

### ISSUE THREAD

**Issue by bernatfortet** [linearapp/linear-import#41]
While the code in the repo shows support for Clubhouse, I can't find it in the CLI utility.

![image](https://user-images.githubusercontent.com/390010/96287906-70b01b80-0f97-11eb-849a-5bff4f5da132.png)

**Comment by rlargman** [comment]
I bumped the version, so the new updates should be in there now! Try updating and lmk if it's still not there.

**Comment by bernatfortet** [comment]
Worked great! Thanks for the quick reply.
I guess image upload is still not working:

![image](https://user-images.githubusercontent.com/390010/96290525-963f2400-0f9b-11eb-8821-c1823c184546.png)

**Comment by rlargman** [comment]
Hmm that should be working. Did you input your Clubhouse API key?

**Comment by rlargman** [comment]
Oh yeah I see it in the above screenshot, and the error because of the `application/json` MIME type. Will see if I can update that.

**Comment by jorilallo** [comment]
@bernatfortet I removed your screenshot as it exposed CH tokens just in case

**Comment by bernatfortet** [comment]
Woops, thanks.

**Comment by rlargman** [comment]
@bernatfortet image uploads should work now! Lmk if you still see issues

**Comment by bernatfortet** [comment]
Should I run the command again? Will it preserve any organization I've made?

Also, what about importing done tasks? We have +5k stories in clubhouse, but only seeing ~1700 in linear

**Comment by bernatfortet** [comment]
Getting the same message after upgrading the package
![image](https://user-images.githubusercontent.com/390010/96321846-bbe42180-0fcb-11eb-99ce-94f3c761880e.png)

**Comment by rlargman** [comment]
Any organizations you made will be preserved, but running the command again will reimport your tasks. That means there will be duplicates of already imported tasks if you run it again within the same team. I've fixed the error you included above, but for the particular file that you mentioned earlier, the image upload will still fail. This is because the image url has been changed (302 redirect), and we don't currently handle that in our upload an image from a url process. That being said, the tasks will still be imported, but not images that have the 302 redirects.

It should be importing `Done` tasks as well. However, Clubhouse doesn't export archived tasks, so if your tasks are `Done` and also archived, those won't be imported. How many lines does your CSV export from Clubhouse have? That should match the number of tasks imported if things are working well.

**Comment by bernatfortet** [comment]
I see. That makes sense. Thanks for clarifying.

**Comment by tommoor** [comment]
> I removed your screenshot as it exposed CH tokens just in case

Token/image is still there in the edit history btw.

**Comment by bernatfortet** [comment]
Good catch, I deleted it from the history.
